#!/bin/sh

export XDEBUG_CONFIG="idekey=XDebugClient"
OPTS="-d extension=php_gtk2.so -d zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20060613/xdebug.so -d xdebug.show_exception_trace=On -d xdebug.remote_enable=On -d xdebug."
/usr/local/bin/php $OPTS run.phpw $@
